import type { MarketplaceListing } from "@/lib/types";

export const marketplaceListings: MarketplaceListing[] = [
  {
    id: "barber-noor-lane",
    slug: "noor-lane",
    kind: "barber",
    name: "Noor Lane",
    tagline: "Precision fades for textured and coily hair.",
    description:
      "Noor focuses on shape retention, clean taper work, and cuts that read sharp after the first week. Her profile is built for clients who want consistency and strong consultation.",
    verified: true,
    rating: 4.9,
    reviewCount: 128,
    profileCompleteness: 96,
    priceBand: "under-70",
    priceBandLabel: "$55-$70",
    bookingUrl: "https://example.com/noor-lane",
    specialties: ["Skin fades", "Textured crop", "Beard shaping"],
    hairTypes: ["Coily", "Curly", "Textured"],
    styles: ["skin-fade", "textured-crop", "beard"],
    languages: ["English", "Arabic"],
    services: [
      { name: "Fade and finish", price: "$60", duration: "45 min" },
      { name: "Fade plus beard", price: "$72", duration: "60 min" },
      { name: "Consultation cut", price: "$68", duration: "50 min" },
    ],
    location: {
      city: "Brooklyn",
      neighborhood: "Fort Greene",
      state: "NY",
      distanceMiles: 2.3,
    },
  },
  {
    id: "shop-atelier-grey",
    slug: "atelier-grey",
    kind: "shop",
    name: "Atelier Grey",
    tagline: "Editorial salon energy with technical color and sculpted cuts.",
    description:
      "Atelier Grey balances salon polish with neighborhood warmth. The team specializes in color-aware consulting, short precision cuts, and premium guest experience.",
    verified: true,
    rating: 4.8,
    reviewCount: 214,
    profileCompleteness: 93,
    priceBand: "70-plus",
    priceBandLabel: "$70+",
    bookingUrl: "https://example.com/atelier-grey",
    specialties: ["Color work", "Precision bob", "Scissor cut"],
    hairTypes: ["Straight", "Wavy", "Curly"],
    styles: ["precision-bob", "scissor-cut", "color"],
    languages: ["English", "French"],
    services: [
      { name: "Precision cut", price: "$95", duration: "60 min" },
      { name: "Gloss and shape", price: "$120", duration: "75 min" },
      { name: "Creative color consult", price: "$85", duration: "45 min" },
    ],
    location: {
      city: "Brooklyn",
      neighborhood: "Williamsburg",
      state: "NY",
      distanceMiles: 3.4,
    },
    team: ["Maya S.", "Felix R.", "June W."],
  },
  {
    id: "barber-mateo-reed",
    slug: "mateo-reed",
    kind: "barber",
    name: "Mateo Reed",
    tagline: "Braids, loc maintenance, and detail-driven grooming.",
    description:
      "Mateo works at the overlap of barbering and protective styling. Clients come for loc cleanup, braid prep, and polished grooming that respects texture and scalp health.",
    verified: true,
    rating: 4.7,
    reviewCount: 91,
    profileCompleteness: 89,
    priceBand: "70-plus",
    priceBandLabel: "$70+",
    bookingUrl: "https://example.com/mateo-reed",
    specialties: ["Loc maintenance", "Braids", "Lineups"],
    hairTypes: ["Coily", "Textured"],
    styles: ["locs", "braids", "lineup"],
    languages: ["English", "Spanish"],
    services: [
      { name: "Retwist and cleanup", price: "$110", duration: "90 min" },
      { name: "Braid refresh", price: "$95", duration: "75 min" },
      { name: "Lineup", price: "$35", duration: "20 min" },
    ],
    location: {
      city: "Jersey City",
      neighborhood: "Downtown",
      state: "NJ",
      distanceMiles: 8.1,
    },
  },
  {
    id: "shop-club-eight",
    slug: "club-eight",
    kind: "shop",
    name: "Club Eight",
    tagline: "High-volume barbershop with strong fade work and late hours.",
    description:
      "Club Eight is built for clients who want a reliable local rotation. The team leans into clean fades, sharp tapers, beard work, and walk-in-friendly pacing.",
    verified: false,
    rating: 4.5,
    reviewCount: 146,
    profileCompleteness: 82,
    priceBand: "under-50",
    priceBandLabel: "Under $50",
    bookingUrl: "https://example.com/club-eight",
    specialties: ["Taper fade", "Buzz cut", "Beard work"],
    hairTypes: ["Straight", "Wavy", "Curly"],
    styles: ["taper-fade", "buzz-cut", "beard"],
    languages: ["English", "Spanish"],
    services: [
      { name: "Classic taper", price: "$42", duration: "35 min" },
      { name: "Buzz and edge", price: "$28", duration: "20 min" },
      { name: "Beard trim", price: "$22", duration: "15 min" },
    ],
    location: {
      city: "Newark",
      neighborhood: "Ironbound",
      state: "NJ",
      distanceMiles: 12.2,
    },
    team: ["Dre", "Luis", "Q", "Amir"],
  },
];